### ISSUE TITLE
Improve log output

### ISSUE THREAD

**Issue by ewanharris** [ewanharris/titanium-codemods#1]
Right now the log output is pretty bad, it would be nice to pull in something like [chalk](https://www.npmjs.com/package/chalk) to fancy it up a little

**Comment by jadach1** [comment]
Hi, I would like to work on this issue please.

**Comment by ewanharris** [comment]
Hey @jadach1, thanks for offering to pick this up!

There's only two places where I think this is useful right now

* Highlight the sdk version [here](https://github.com/ewanharris/titanium-codemods/blob/master/cli/commands/run.js#L77)
* Highlight the transform name [here](https://github.com/ewanharris/titanium-codemods/blob/master/cli/commands/run.js#L122)

I tend to use [chalk](https://www.npmjs.com/package/chalk) for adding colors to log output.

You might find it difficult to test if you aren't a titanium user (to test the changes thoroughly you'll need a titanium application). But it's fine if you're not! If you make the PR anyway I can test it myself!

Good luck and feel free to ping me if you need!

**Comment by jadach1** [comment]
Hi again, I submitted a PR, let me know if there are any issues with it.  Thanks.

**Comment by ewanharris** [comment]
Done in #4 
Thanks again @jadach1 	🎉
